const screens = {
  splash: document.getElementById('splash'),
  login: document.getElementById('login'),
  chat: document.getElementById('chat')
};

const state = {
  user: '',
  lang: 'ar'
};

const typewriterEl = document.getElementById('typewriter');
const startBtn = document.getElementById('startBtn');
const loginBtn = document.getElementById('loginBtn');
const usernameInput = document.getElementById('username');
const welcomeEl = document.getElementById('welcome');
const messagesEl = document.getElementById('messages');
const chatForm = document.getElementById('chatForm');
const promptInput = document.getElementById('prompt');
const typingEl = document.getElementById('typing');
const quickActions = document.querySelector('.quick-actions');

const chatLayout = document.getElementById('chatLayout');
const codePanel = document.getElementById('codePanel');
const codeLanguage = document.getElementById('codeLanguage');
const codeEditor = document.getElementById('codeEditor');
const runOutput = document.getElementById('runOutput');

const starterLine = 'نيكسا ليس مجرد عميل… بل هو المستقبل.';

function showScreen(key) {
  Object.values(screens).forEach((s) => s.classList.remove('active'));
  screens[key].classList.add('active');
}

function typeWriter(text, speed = 55) {
  let i = 0;
  const timer = setInterval(() => {
    typewriterEl.textContent = text.slice(0, i++);
    if (i > text.length) clearInterval(timer);
  }, speed);
}

function appendBubble(text, role = 'bot') {
  const bubble = document.createElement('div');
  bubble.className = `bubble ${role}`;
  bubble.textContent = text;
  messagesEl.appendChild(bubble);
  messagesEl.scrollTop = messagesEl.scrollHeight;
}

function waitTyping(ms = 720) {
  typingEl.classList.remove('hidden');
  return new Promise((resolve) => {
    setTimeout(() => {
      typingEl.classList.add('hidden');
      resolve();
    }, ms);
  });
}

function detectLanguage(text) {
  return /[\u0600-\u06FF]/.test(text) ? 'ar' : 'en';
}

function detectCodeIntent(text) {
  const keywords = ['كود', 'code', 'function', 'python', 'javascript', 'flutter', 'kotlin', 'react', 'api'];
  return keywords.some((k) => text.toLowerCase().includes(k));
}

function inferLanguage(text) {
  const map = ['python', 'javascript', 'typescript', 'cpp', 'java', 'dart', 'kotlin', 'swift', 'html', 'css'];
  return map.find((m) => text.toLowerCase().includes(m)) || 'JavaScript';
}

function openCodeMode(lang, snippet) {
  chatLayout.classList.add('split');
  codePanel.classList.remove('hidden');
  codeLanguage.textContent = lang;
  codeEditor.value = snippet;
}

function closeCodeMode() {
  chatLayout.classList.remove('split');
  codePanel.classList.add('hidden');
  runOutput.textContent = '';
}

function apkWorkflow() {
  return `Workflow تحويل مشروع إلى APK:
1) اختيار التقنية: Flutter أو Kotlin Native.
2) إنشاء المشروع + package name مناسب.
3) إعداد AndroidManifest + الصلاحيات.
4) إضافة App Icon + Splash Screen.
5) Build Release: flutter build apk --release أو Gradle assembleRelease.
6) توقيع التطبيق keystore.
7) اختبار APK على جهاز حقيقي.
8) تجهيز Google Play: وصف + لقطات + سياسة الخصوصية.
9) رفع AAB/APK على Play Console ونشر النسخة.`;
}

function botReply(text) {
  const lang = detectLanguage(text);
  state.lang = lang;
  const lc = text.toLowerCase();

  if (lc.includes('اعمللي تطبيق') || lc.includes('ابلكيشن') || lc.includes('apk')) {
    return `تمام 👨‍💻\nعايزه Android ولا iOS؟\nFlutter ولا Native؟\nقول الفكرة وخليني أبنيها صح.\n\n${apkWorkflow()}`;
  }

  if (lc.includes('bug')) {
    return lang === 'ar'
      ? 'في Bug مستخبي هنا 👀\nسيبه عليا. ابعتلي الرسالة والخطأ وأنا أعمل Debug كامل.'
      : 'There is a hidden bug 👀\nLeave it to me. Share the stack trace and I will debug it end-to-end.';
  }

  if (lc.includes('project') || lc.includes('مشروع')) {
    return lang === 'ar'
      ? 'جاهز نبني حاجة تقيلة 🔥\nقولي التفاصيل وأنا أظبطلك المعمارية + خطة التنفيذ.'
      : 'Ready to build something big 🔥\nShare requirements and I will craft architecture + implementation plan.';
  }

  if (detectCodeIntent(text)) {
    const detected = inferLanguage(text);
    const snippet = `// ${detected} starter generated by Nexa\nfunction solveTask() {\n  console.log('Nexa is ready');\n}`;
    openCodeMode(detected, snippet);
    return lang === 'ar'
      ? 'تمام يا بطل 👑\nفتحتلك وضع الأكواد الذكي مع أدوات Copy / Download / Run.'
      : 'Done champ 👑\nSmart code mode is now open with Copy / Download / Run tools.';
  }

  return lang === 'ar'
    ? `أنا Nexa — مساعدك البرمجي العالمي.\nأقدر أبني مشاريع، APIs، قواعد بيانات، أدوات AI، وأجهز Workflow APK من الصفر.`
    : 'I am Nexa — your global engineering copilot. I can build full apps, APIs, databases, AI tools, and complete APK workflows.';
}

startBtn.addEventListener('click', () => showScreen('login'));
loginBtn.addEventListener('click', async () => {
  const name = usernameInput.value.trim();
  if (!name) return;
  state.user = name;
  showScreen('chat');
  welcomeEl.textContent = `أهلًا يا ${name} 👋 جاهز نكسر الدنيا؟ 🔥`;
  appendBubble('تمام يا بطل 👑\nخلينا نعمل حاجة تقيلة.', 'bot');
  appendBubble(apkWorkflow(), 'bot');
  await waitTyping(450);
});

chatForm.addEventListener('submit', async (e) => {
  e.preventDefault();
  const text = promptInput.value.trim();
  if (!text) return;
  appendBubble(text, 'me');
  promptInput.value = '';
  await waitTyping();
  appendBubble(botReply(text), 'bot');
});

quickActions.addEventListener('click', async (e) => {
  const action = e.target.dataset.action;
  if (!action) return;
  await waitTyping(380);
  if (action === 'apk') appendBubble(apkWorkflow(), 'bot');
  if (action === 'project') appendBubble('جاهز نبني حاجة تقيلة 🔥\nابعت الفكرة + المنصة المستهدفة.', 'bot');
  if (action === 'bug') appendBubble('في Bug مستخبي هنا 👀\nابعت Stack Trace وهصلحه.', 'bot');
});

document.getElementById('closeCode').addEventListener('click', closeCodeMode);
document.getElementById('copyCode').addEventListener('click', async () => {
  await navigator.clipboard.writeText(codeEditor.value);
});
document.getElementById('downloadCode').addEventListener('click', () => {
  const blob = new Blob([codeEditor.value], { type: 'text/plain' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `nexa-snippet.${String(codeLanguage.textContent).toLowerCase() === 'python' ? 'py' : 'js'}`;
  a.click();
  URL.revokeObjectURL(a.href);
});
document.getElementById('runCode').addEventListener('click', () => {
  runOutput.textContent = 'Running...';
  try {
    const logs = [];
    const original = console.log;
    console.log = (...args) => logs.push(args.join(' '));
    // eslint-disable-next-line no-eval
    eval(codeEditor.value);
    console.log = original;
    runOutput.textContent = logs.join('\n') || 'Done (no output).';
  } catch (err) {
    runOutput.textContent = `Error: ${err.message}`;
  }
});

(function particles() {
  const c = document.getElementById('particles');
  const ctx = c.getContext('2d');
  let w = c.width = window.innerWidth;
  let h = c.height = window.innerHeight;
  const dots = Array.from({ length: 70 }, () => ({
    x: Math.random() * w,
    y: Math.random() * h,
    r: Math.random() * 1.8 + 0.6,
    vx: (Math.random() - 0.5) * 0.35,
    vy: (Math.random() - 0.5) * 0.35,
  }));

  function tick() {
    ctx.clearRect(0, 0, w, h);
    dots.forEach((d) => {
      d.x += d.vx;
      d.y += d.vy;
      if (d.x < 0 || d.x > w) d.vx *= -1;
      if (d.y < 0 || d.y > h) d.vy *= -1;
      ctx.beginPath();
      ctx.arc(d.x, d.y, d.r, 0, Math.PI * 2);
      ctx.fillStyle = 'rgba(143, 111, 255, 0.75)';
      ctx.fill();
    });
    requestAnimationFrame(tick);
  }

  window.addEventListener('resize', () => {
    w = c.width = window.innerWidth;
    h = c.height = window.innerHeight;
  });

  tick();
})();

typeWriter(starterLine);
